import {useEffect,useState} from 'react';
import {supabase,makeCode} from './lib/supabase';
import './styles.css';

type Room={id:string;code:string;host_id:string;game:string;state:string;round:number;sound_on:boolean}; type Player={id:string;name:string;avatar:string;title:string;ready:boolean;score:number;lives:number;ammo:number};
const games=['Gun Battle','Meme vs Meme']; const avatars=['🦊','🐸','👾','🐼','🦄','🐙'];
export default function App(){const [mode,setMode]=useState<'home'|'host'|'player'>('home'); const [code,setCode]=useState(''); const [room,setRoom]=useState<Room|null>(null); const [players,setPlayers]=useState<Player[]>([]); const [name,setName]=useState(''); const [me,setMe]=useState<Player|null>(null); const [avatar,setAvatar]=useState(avatars[0]);
 async function create(){let c=''; for(let i=0;i<12;i++){const candidate=makeCode(); const {data}=await supabase.from('rooms').select('id').eq('code',candidate).is('ended_at',null).maybeSingle(); if(!data){c=candidate;break}} if(!c)return; const {data}=await supabase.from('rooms').insert({code:c,game:games[0]}).select().single(); if(data){setRoom(data);setMode('host')}}
 async function join(){const {data}=await supabase.from('rooms').select('*').eq('code',code.toUpperCase()).is('ended_at',null).maybeSingle(); if(data){setRoom(data);setMode('player')}}
 useEffect(()=>{if(!room)return; const load=async()=>{const {data}=await supabase.from('room_players').select('*').eq('room_id',room.id).order('joined_at');setPlayers(data??[])};load(); const ch=supabase.channel('room-'+room.id).on('postgres_changes',{event:'*',schema:'public',table:'rooms',filter:'id=eq.'+room.id},p=>{if(p.new)setRoom(p.new as Room)}).on('postgres_changes',{event:'*',schema:'public',table:'room_players',filter:'room_id=eq.'+room.id},load).subscribe(); return()=>{supabase.removeChannel(ch)}},[room?.id]);
 async function enter(){if(!room||!name.trim())return; const {data}=await supabase.from('room_players').insert({room_id:room.id,name:name.trim(),avatar}).select().single();if(data)setMe(data)}
 async function setState(state:string){if(room)await supabase.from('rooms').update({state}).eq('id',room.id)}
 if(mode==='home')return <main className="home"><h1>SNOWY <i>PARTY</i></h1><p>Jackbox-style chaos. Host on the big screen, play from your phone.</p><button onClick={create}>Create host room</button><div className="join"><input maxLength={4} value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="ABCD"/><button onClick={join}>Join room</button></div></main>;
 if(mode==='player')return <main className="phone"><small>ROOM {room?.code}</small>{!me?<><h1>Join the party</h1><input value={name} onChange={e=>setName(e.target.value)} placeholder="Display name"/><div className="avatars">{avatars.map(a=><button className={a===avatar?'chosen':''} onClick={()=>setAvatar(a)}>{a}</button>)}</div><button onClick={enter}>Ready up</button></>:<Controller room={room!} me={me}/>} </main>;
 return <main className="host"><header><div><small>ROOM CODE</small><strong>{room?.code}</strong><p>Scan or visit this page on your phone to join</p></div><div className="qr">▦<small>/join/{room?.code}</small></div></header><section className="state"><span>{room?.state.replace('_',' ')}</span>{room?.state==='lobby'?<button onClick={()=>setState('countdown')}>Start {room.game}</button>:<div className="count">{room?.state==='countdown'?'3':'LIVE'}</div>}</section><section className="players">{players.map(p=><article><span>{p.avatar}</span><b>{p.name}</b><small>{p.title} {p.ready?'✓ READY':''}</small><button onClick={()=>supabase.from('room_players').delete().eq('id',p.id)}>Kick</button></article>)}{!players.length&&<p>Waiting for players to join…</p>}</section><footer><select value={room?.game} onChange={e=>supabase.from('rooms').update({game:e.target.value}).eq('id',room!.id)}>{games.map(g=><option>{g}</option>)}</select><button onClick={()=>supabase.from('rooms').update({sound_on:!room?.sound_on}).eq('id',room!.id)}>Sound {room?.sound_on?'on':'off'}</button><button onClick={()=>supabase.rpc('end_room',{room_uuid:room!.id})}>End room</button></footer></main>}
function Controller({room,me}:{room:Room;me:Player}){return <><h1>{room.game}</h1><p>Round {room.round} · {room.state}</p><div className="stats">❤️ {me.lives} · 🔫 {me.ammo} · ⭐ {me.score}</div><div className="actions">{['Shoot','Reload','Shield','Money'].map(a=><button>{a}</button>)}</div><button className="shop">Shop: Auto-Shield · Shield Remover · +1 Life</button>{room.game==='Meme vs Meme'&&<textarea placeholder="Record or remix your meme prompt…"/>}</>}
