import { useState } from 'react';
import { Gamepad2, ShoppingBag, Music2, History, UserRound, Users, Sparkles, Volume2, ArrowLeft, Coins, Trophy, Play, Copy, Shield, Zap } from 'lucide-react';

type View='landing'|'lobby'|'game'|'shop'|'vault'|'history'|'profile';
type Props={view:View; setView:(v:View)=>void};
const games=[{name:'Gun Battle',desc:'Read the room. Shoot, shield, reload.',icon:'🔫',color:'cyan'},{name:'Meme vs Meme',desc:'Drop the funniest meme. Win the crowd.',icon:'😂',color:'purple'},{name:'Audio Royale',desc:'Identify the sound before anyone else.',icon:'🎧',color:'pink'}];
const nav=[['landing','Play'],['shop','Shop'],['vault','Vault'],['history','Past games'],['profile','Profile']];
function Shell({view,setView,children}:{view:View;setView:(v:View)=>void;children:React.ReactNode}){return <div className="app"><aside><button className="brand" onClick={()=>setView('landing')}><span className="logo">❄</span><span><b>SNOWY<br/>PARTY</b><small>the lobby is open</small></span></button><nav>{nav.map(([id,label],i)=><button className={view===id?'active':''} onClick={()=>setView(id as View)} key={id}>{[<Gamepad2/>,<ShoppingBag/>,<Music2/>,<History/>,<UserRound/>][i]}<span>{label}</span></button>)}</nav><div className="side-note"><Sparkles/><b>Party coins</b><span>Spend them on flexes, not responsibilities.</span></div><div className="mini-user"><span className="avatar">S</span><span><b>Snowy</b><small>Guest player</small></span><strong>2,450</strong></div></aside><main><header><div><span className="eyebrow">WEDNESDAY NIGHT // READY UP</span><h1>{view==='landing'?'Make some noise.':view==='lobby'?'Room lobby':view==='game'?'Live game':view==='shop'?'Party shop':view==='vault'?'Audio vault':view==='history'?'Past games':'Your profile'}</h1></div><div className="top-actions"><span className="wallet"><Coins size={15}/> 2,450</span><button className="icon-btn" onClick={()=>setView('profile')}><span className="avatar">S</span></button></div></header>{children}</main></div>}
export default function App(){const [view,setView]=useState<View>('landing');const [code,setCode]=useState('');const [room,setRoom]=useState('SNOW');const [mode,setMode]=useState('Gun Battle');const [started,setStarted]=useState(false);const join=()=>{if(code.length===4){setRoom(code.toUpperCase());setView('lobby')}};return <Shell view={view} setView={setView}>{view==='landing'&&<Landing code={code} setCode={setCode} join={join} setView={setView}/>} {view==='lobby'&&<Lobby room={room} mode={mode} setMode={setMode} setView={setView} started={started} setStarted={setStarted}/>} {view==='game'&&<Game mode={mode} setView={setView}/>} {view==='shop'&&<Shop/>}{view==='vault'&&<Vault/>}{view==='history'&&<HistoryView/>}{view==='profile'&&<Profile/>}</Shell>}
function Landing({code,setCode,join,setView}:any){return <><section className="hero"><div><span className="pill">✦ PARTY PORTAL ONLINE</span><h2>Bring your<br/><em>chaos.</em></h2><p>One room. Infinite clips. Questionable decisions. Gather the crew and make some memories.</p><div className="join-row"><input maxLength={4} value={code} onChange={e=>setCode(e.target.value.replace(/[^a-z0-9]/gi,'').slice(0,4))} placeholder="ROOM CODE"/><button className="primary" onClick={join}>Join game <Play size={16}/></button></div><button className="text-button" onClick={()=>setView('lobby')}>＋ Host a new game <span>no display name needed</span></button></div><div className="hero-art">🎉<small>LET'S<br/>GET<br/>WEIRD</small></div></section><div className="section-title"><span className="eyebrow">JUMP BACK IN</span><h2>Choose your chaos</h2></div><div className="game-grid">{games.map(g=><article className={'game-card '+g.color}><div className="game-icon">{g.icon}</div><h3>{g.name}</h3><p>{g.desc}</p><button className="secondary full" onClick={()=>setView('lobby')}>View game <ArrowLeft size={15}/></button></article>)}</div></>}
function Lobby({room,mode,setMode,setView,started,setStarted}:any){return <><div className="room-banner"><div><span className="eyebrow">ROOM CODE</span><strong>{room}</strong><button className="icon-btn"><Copy size={16}/></button></div><span className="pill">4 players online</span></div><div className="room-layout"><section className="panel"><span className="eyebrow">PLAYERS IN ROOM</span>{['Snowy · host','Mia','Derek','Avery'].map((x,i)=><div className="player" key={x}><span className="avatar">{x[0]}</span><b>{x}</b>{i===0&&<small>HOST</small>}</div>)}<button className="secondary full">＋ Invite friends</button></section><section className="panel"><span className="eyebrow">SELECT A GAME</span><div className="mode-list">{games.map(g=><button className={mode===g.name?'selected':''} onClick={()=>setMode(g.name)} key={g.name}><span>{g.icon}</span><div><b>{g.name}</b><small>{g.desc}</small></div><span>›</span></button>)}</div><button className="primary full" onClick={()=>{setStarted(true);setView('game')}}>{started?'Restart game':'Start '+mode} <Zap size={16}/></button></section></div></>}
function Game({mode,setView}:Props&{mode:string}){return <section className="game-stage"><button className="back" onClick={()=>setView('lobby')}><ArrowLeft size={15}/> Back to lobby</button><div className="game-title"><span className="pill">ROUND 03 / 05</span><h2>{mode}</h2><p>Everyone is locked in. Make your move.</p></div><div className="arena"><div className="versus"><div><span className="big-avatar">S</span><b>You</b><small>❤️ ❤️ ❤️</small></div><strong>VS</strong><div><span className="big-avatar purple">M</span><b>Mia</b><small>❤️ ❤️</small></div></div><div className="action-row"><button>🔫 Shoot</button><button>♻ Reload</button><button>🛡 Shield</button></div></div><div className="reward-row"><span><Trophy size={18}/> Winner gets <strong>+500 coins</strong></span><span><Volume2 size={18}/> Party audio is on</span></div></section>}
function Shop(){return <><div className="shop-head"><p>Spend party coins on cosmetics that say “I definitely planned that.”</p><span className="wallet"><Coins size={15}/> 2,450 available</span></div><div className="shop-grid">{[['⚡','Neon Menace','Title','350'],['🌈','Rainbow Riot','Banner','600'],['👑','Crown Behavior','Badge','900'],['🧊','Ice Cold','Title','250'],['💿','Main Character','Banner','750'],['🔥','Unhinged','Badge','1,200']].map(x=><article className="shop-card"><div className="item-art">{x[0]}</div><span className="eyebrow">{x[2]}</span><h3>{x[1]}</h3><button className="primary full"><Coins size={14}/>{x[3]} Buy</button></article>)}</div></>}
function Vault(){return <section className="panel vault"><div className="vault-head"><div><span className="eyebrow">YOUR SOUNDBOARD</span><h2><Music2/> Audio Vault</h2><p>Load the clips that make your group lose it.</p></div><button className="primary">＋ Add audio</button></div>{['vine boom.mp3','dramatic chipmunk.wav','suspiciously funky.mp3','airhorn_final_final.mp3'].map((x,i)=><div className="audio-row"><button className="circle">▶</button><div><b>{x}</b><small>Added {i+1} days ago · 3 plays</small></div><span className="pill">HOTKEY {i+1}</span><button className="icon-btn">⋮</button></div>)}</section>}
function HistoryView(){return <><div className="stats"><div><small>GAMES PLAYED</small><b>47</b></div><div><small>WIN RATE</small><b>64%</b></div><div><small>PARTY COINS EARNED</small><b>18,250</b></div></div><section className="panel"><span className="eyebrow">RECENT MATCHES</span>{[['🔫','Gun Battle','Won · 3 rounds','+500'],['😂','Meme vs Meme','2nd place · 5 rounds','+250'],['🎧','Audio Royale','Won · 7 rounds','+500'],['🔫','Gun Battle','3rd place · 3 rounds','+100']].map(x=><div className="history-row"><span className="history-icon">{x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small></div><strong> {x[3]}</strong></div>)}</section></>}
function Profile(){return <section className="panel profile"><span className="profile-avatar">S</span><h2>Snowy <span>guest profile</span></h2><p className="title-banner">★ CHAOS COORDINATOR ★</p><div className="stat"><b>2,450</b><small>PARTY COINS</small></div><div className="achievement"><Trophy/><div><b>First Blood</b><small>Win your first Gun Battle</small></div><span>✓</span></div><button className="secondary full">Sign in to save your stats</button></section>}
